# Install script for directory: /Users/yilu/Projects/mysql-server

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/Users/yilu/mysql-bin/5.7")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Debug")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

if("${CMAKE_INSTALL_COMPONENT}" STREQUAL "Info" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/docs" TYPE FILE OPTIONAL FILES "/Users/yilu/Projects/mysql-server/Docs/mysql.info")
endif()

if("${CMAKE_INSTALL_COMPONENT}" STREQUAL "Readme" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/." TYPE FILE OPTIONAL FILES
    "/Users/yilu/Projects/mysql-server/COPYING"
    "/Users/yilu/Projects/mysql-server/LICENSE.mysql"
    )
endif()

if("${CMAKE_INSTALL_COMPONENT}" STREQUAL "Readme" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/." TYPE FILE FILES "/Users/yilu/Projects/mysql-server/README")
endif()

if("${CMAKE_INSTALL_COMPONENT}" STREQUAL "Unspecified" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/docs" TYPE FILE FILES
    "/Users/yilu/Projects/mysql-server/Docs/INFO_SRC"
    "/Users/yilu/Projects/mysql-server/Docs/INFO_BIN"
    )
endif()

if("${CMAKE_INSTALL_COMPONENT}" STREQUAL "Documentation" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/docs" TYPE DIRECTORY FILES "/Users/yilu/Projects/mysql-server/Docs/" REGEX "/makefile\\.[^/]*$" EXCLUDE REGEX "/glibc[^/]*$" EXCLUDE REGEX "/linuxthreads\\.txt$" EXCLUDE REGEX "/myisam\\.txt$" EXCLUDE REGEX "/mysql\\.info$" EXCLUDE REGEX "/sp\\-imp\\-spec\\.txt$" EXCLUDE)
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/Users/yilu/Projects/mysql-server/zlib/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/extra/yassl/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/extra/yassl/taocrypt/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/cmd-line-utils/libedit/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/extra/protobuf/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/storage/archive/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/storage/blackhole/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/storage/csv/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/storage/example/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/storage/federated/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/storage/heap/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/storage/innobase/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/storage/myisam/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/storage/myisammrg/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/storage/ndb/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/storage/partition/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/storage/perfschema/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/plugin/audit_null/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/plugin/auth/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/plugin/connection_control/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/plugin/daemon_example/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/plugin/fulltext/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/plugin/innodb_memcached/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/plugin/keyring/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/plugin/password_validation/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/plugin/replication_observers_example/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/plugin/rewrite_example/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/plugin/rewriter/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/plugin/semisync/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/plugin/test_service_sql_api/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/plugin/test_services/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/plugin/udf_services/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/plugin/version_token/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/rapid/plugin/group_replication/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/rapid/plugin/keyring_udf/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/rapid/plugin/x/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/include/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/dbug/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/strings/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/vio/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/regex/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/mysys/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/mysys_ssl/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/libmysql/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/libbinlogevents/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/libbinlogstandalone/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/unittest/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/unittest/examples/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/unittest/mytap/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/unittest/mytap/t/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/rapid/unittest/gunit/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/extra/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/client/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/sql/share/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/libservices/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/man/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/testclients/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/sql/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/scripts/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/mysql-test/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/mysql-test/lib/My/SafeProcess/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/support-files/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/packaging/rpm-common/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/packaging/rpm-oel/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/packaging/rpm-fedora/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/packaging/rpm-sles/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/packaging/rpm-docker/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/packaging/deb-in/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/packaging/WiX/cmake_install.cmake")
  include("/Users/yilu/Projects/mysql-server/packaging/solaris/cmake_install.cmake")

endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "/Users/yilu/Projects/mysql-server/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
